### ISSUE TITLE
Bag: FileNotFoundError: [Errno 2] No such file or directory: FileNotFoundError: [Errno 2] No such file or directory: 

### ISSUE THREAD

**Issue by yuchenlichuck** [daveredrum/Text2Tex#11]
```
=> initializing input arguments...
=> OUTPUT_DIR: outputs/backpack/42-p36-h20-1.0-0.3-0.1
=> loading target mesh...
=> initializing ControlNet Depth...
ControlLDM: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Traceback (most recent call last):
  File "/home/dubaiprince/Projects/Text2Tex/scripts/generate_texture.py", line 225, in <module>
    controlnet, ddim_sampler = get_controlnet_depth()
  File "/home/dubaiprince/Projects/Text2Tex/./lib/diffusion_helper.py", line 25, in get_controlnet_depth
    model, ddim_sampler = init_model()
  File "/home/dubaiprince/Projects/Text2Tex/./models/ControlNet/gradio_depth2image.py", line 28, in init_model
    state_dict = load_state_dict(BASE_DIR+'/models/control_sd15_depth.pth')
  File "/home/dubaiprince/Projects/Text2Tex/models/ControlNet/cldm/model.py", line 18, in load_state_dict
    state_dict = get_state_dict(torch.load(ckpt_path, map_location=torch.device(location)))
  File "/home/dubaiprince/miniconda3/envs/text2tex/lib/python3.9/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/dubaiprince/miniconda3/envs/text2tex/lib/python3.9/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/dubaiprince/miniconda3/envs/text2tex/lib/python3.9/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))

```

perhaps you need to complete the controlnet pth downloading process.

**Comment by daveredrum** [comment]
Hi @yuchenlichuck, to use the ControlNet Depth2img model, please download `control_sd15_depth.pth` from the [hugging face page](https://huggingface.co/lllyasviel/ControlNet/tree/main/models), and put it under `models/ControlNet/models/`.
